on: push
jobs:
    build-container:
        name: Build container
        runs-on: ubuntu-latest
        steps:
        -   name:   Checkout code
            uses:   actions/checkout@v3
        -   name:   Login to Docker Hub
            uses:   docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -   name:   Build and push to Docker hub
            uses:   docker/build-push-action@v2
            with:
                context: .
                push:   true
                tags: user/image:tag, user/image:${{ github.run_number }}
                
                
                - name: Push dockerhub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: seaman69/3dspace
        tags: objetosv2
        registry: docker.io
        username: ${{secrets.DOCKER_MAIL}}
        password: ${{ secrets.DOCKER_PASSWD }}
